### ISSUE TITLE
Запуск программы.

### ISSUE THREAD

**Issue by AlexeySorokin** [Vitalgor/LR1#1]
Добавьте возможность запуска программы как парсера: грамматика подаётся как первый аргумент командной строки, слова подаются через `stdin` (пустое слово тоже может быть подано).

**Comment by Vitalgor** [comment]
Добавлено. Инструкцию к применению можно найти в readme.md

**Comment by AlexeySorokin** [comment]
Добавьте в тесты пример файла с грамматикой: пока не удалось запустить.

**Comment by Vitalgor** [comment]
Файл добавлен в папку src. 
http://prntscr.com/qltuky
Пример того, как запускается парсер.
