### ISSUE TITLE
Ошибка алгоритма

### ISSUE THREAD

**Issue by AlexeySorokin** [Vitalgor/LR1#3]
Проверьте, что не так с приложенным файлом.
[input.txt](https://github.com/Vitalgor/LR1/files/4049184/input.txt)

**Comment by Vitalgor** [comment]
Уберите перенос строки в конце
Алгоритм считает, что вы дали пустое правило

**Comment by Vitalgor** [comment]
Я убрал, все заработало

**Comment by Vitalgor** [comment]
Более того, грамматика не соответствует Вашему замечанию из лекций: стартовый символ не участвует ни в каких правилах, кроме S'->S. Я не сразу понял, почему алгоритм отвергает все слова. Добавил это правило, и все стало приниматься.

**Comment by AlexeySorokin** [comment]
Условие на стартовый нетерминал надо тогда прописывать в `readme`, либо создавать выделенный нетерминал, используемый только как стартовый.
